// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodigoComun.Entities
{
    public partial class Deposito
    {
        public Deposito()
        {
            Stocks = new HashSet<Stock>();
        }

        public int Id { get; set; }
        public decimal? Capacidad { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }

        public virtual ICollection<Stock> Stocks { get; set; }
    }
}