// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CodigoComun.Modelo;
using System;
using System.Collections.Generic;

namespace CodigoComun.Entities
{
    public partial class Stock
    {
        public int Id { get; set; }
        public int? IdArticulo { get; set; }
        public int? IdDeposito { get; set; }
        public decimal? Cantidad { get; set; }

        public virtual Deposito IdDepositoNavigation { get; set; }
    }
}